### ISSUE TITLE
Maintiain compatability with the WHO 2022 Questionnaire

### ISSUE THREAD

**Issue by rileyhazard** [ihmeuw/SmartVA-Analyze#12]
SmartVA-Analyze currently supports the PHMRC short, PHMRC long, or WHO 2016 questionnaire as an input csv. The WHO 2022 VA questionnaire proposes the removal of several questions used in cause of death prediction by the Tariff 2.0 algorithm: https://www.who.int/standards/classifications/other-classifications/verbal-autopsy-standards-ascertaining-and-attributing-causes-of-death-tool

**Comment by aflaxman** [comment]
I tried running the existing code on the WHO 2022 data you sent me this morning (from the command line) and it worked!  No warnings and reasonable answers.  So maybe we are already compatible with the updated form!

![image](https://user-images.githubusercontent.com/51236/206523666-677a1fc3-ccd2-4a26-ad31-1d129bb86b5b.png)

**Comment by aflaxman** [comment]
I made a pull request from Riley's code on this, and have now merged it.
