### ISSUE TITLE
Number of months pregnant (WHO questionnaire)

### ISSUE THREAD

**Issue by rileyhazard** [ihmeuw/SmartVA-Analyze#16]
The WHO 2016 (and 2022) VA questionnaire asks the question `(Id10309) For how many months was she pregnant?` which maps to `adult_3_11a` in the PHMRC questionnaire. Reports of higher than expected maternal deaths when using the WHO 2016 questionnaire have identified a bug in the processing of `Id10309`.

The WHO 2016/2022 questionnaire provides the user instructions to answer 88 or 99 if the answer is refused or unknown, respectively. Because the upper bound for months pregnant (10 months) is contained within the PHMRC questionnaire, 88 and 99 are recognized as valid months pregnant within SmartVA. A custom mapping in `who_prep.py` is suggested to create an upper bound for months pregnant when mapping the WHO questionnaire.

**Comment by aflaxman** [comment]
Great idea, thanks Riley.

**Comment by aflaxman** [comment]
I have added code for this while updating SVA to use the WHO 2022 questionnaire, see commit c08419d5fc1e9735de69570da43d7a49b0c4bc7b
