### ISSUE TITLE
codebook for causes in tariff symptom-cause database

### ISSUE THREAD

**Issue by y-chu** [ihmeuw/SmartVA-Analyze#7]
hello,

I'm wondering if there's a complete list of what the causes (cause1 to cause46 in variable xs_name) and the symptoms are in the tariff matrix please. 
https://github.com/ihmeuw/SmartVA-Analyze/blob/master/smartva/data/tariffs-adult.csv

Thanks,
Sophia

**Comment by rileyhazard** [comment]
Hi Sophia,

[CAUSE_46](https://github.com/ihmeuw/SmartVA-Analyze/blob/c69dc5840cc9bd17f36239705196807ffb2c11f4/smartva/data/adult_tariff_data.py#L843) is a dictionary at the 46 cause level in adult_tariff_data.py

[SYMPTOM_DESCRIPTIONS](https://github.com/ihmeuw/SmartVA-Analyze/blob/c69dc5840cc9bd17f36239705196807ffb2c11f4/smartva/data/adult_tariff_data.py#L991) is a dictionary of the definitions of each symptom also in  adult_tariff_data.py.

You can find the cause names and symptom descriptions for children and neonates in their respective files.

I hope this helps.

Cheers,
Riley

**Comment by y-chu** [comment]
Thanks much! That's what I'm looking for!
